name = "palamedes"
version = "0.1.0"
defaultTargets = ["palamedes"]

[[lean_lib]]
name = "Palamedes"

[[lean_exe]]
name = "palamedes"
root = "Main"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "556fca241ed175a5bf96d02693569f2ec22bfebd"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.15.0"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "v4.15.0"

[[require]]
name = "ssreflect"
git = "https://github.com/verse-lab/leanssr"
rev = "v4.15.0"